server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 12MB


# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.heap.forum.pojo

# 日志配置
logging:
  level:
    cn.heap.forum: debug
    com.baomidou.mybatisplus: debug
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%thread] %-5level %logger{36} - %msg%n"

pagehelper:
  helperDialect: mysql  # 数据库类型（mysql/oracle/pgsql等）
  reasonable: true      # 合理分页（默认false）
  supportMethodsArguments: true  # 支持方法入参
  params: count=countSql  # 分页参数

file:
  upload-dir: D:/load/images